local ShopConfig = {
	Categories = {
		Weapons = {
			{ Name = "Pistol", Price = 500, Description = "Standard sidearm.", Subcategory = "Ranged" },
			{ Name = "SMG", Price = 3000, Description = "Fast firing close quarters weapon.", Subcategory = "Ranged" },
			{ Name = "AR", Price = 5000, Description = "Standard Assault Rifle.", Subcategory = "Ranged" },
			{ Name = "Scar", Price = 8500, Description = "High damage automatic rifle.", Subcategory = "Ranged" },
			{ Name = "Shotgun", Price = 7000, Description = "Dominates in close range.", Subcategory = "Ranged" },
			{ Name = "Sniper", Price = 12000, Description = "One shot, one kill.", Subcategory = "Ranged" },

			{ Name = "Wooden Knife", Price = 100, Description = "A basic wooden knife.", Subcategory = "Melee" },
			{ Name = "Knife", Price = 250, Description = "Standard combat knife.", Subcategory = "Melee" },
			{ Name = "Metal Knife", Price = 500, Description = "A sharp metal knife for close combat.", Subcategory = "Melee" },
			{ Name = "Wooden Axe", Price = 250, Description = "Good for chopping wood.", Subcategory = "Melee" },
			{ Name = "Axe", Price = 1000, Description = "Standard versatile axe.", Subcategory = "Melee" },
			{ Name = "Metal Axe", Price = 2500, Description = "Heavy metal axe.", Subcategory = "Melee" },
			{ Name = "Wooden Bat", Price = 200, Description = "Batter up!", Subcategory = "Melee" },
			{ Name = "Metal Bat", Price = 800, Description = "Sturdy metal bat.", Subcategory = "Melee" },
			{ Name = "Spiked Bat", Price = 1500, Description = "Ouch.", Subcategory = "Melee" }
		},
		Skins = {},
		Effects = {}
	}
}

return ShopConfig